spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/todayit?currentSchema=${DB_SCHEMA:todayit}}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/local
