CREATE TABLE place (
    place_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    address VARCHAR(255) NOT NULL,
    category VARCHAR(30) NOT NULL,
    view_count INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_place_category CHECK (
        category IN (
            'RESTAURANT',
            'CAFE_DESSERT',
            'BAR',
            'EXHIBITION_CULTURE',
            'MOVIE_PERFORMANCE',
            'EXPERIENCE_WORKSHOP',
            'PLAY_ACTIVITY',
            'NATURE_WALK',
            'SHOPPING',
            'LANDMARK_VIEW',
            'RELAXATION_SPA'
        )
    )
);

COMMENT ON TABLE place IS '장소';
COMMENT ON COLUMN place.place_id IS '장소 식별자';
COMMENT ON COLUMN place.name IS '장소명';
COMMENT ON COLUMN place.latitude IS '위도';
COMMENT ON COLUMN place.longitude IS '경도';
COMMENT ON COLUMN place.address IS '주소';
COMMENT ON COLUMN place.category IS '카테고리';
COMMENT ON COLUMN place.view_count IS '조회수';
COMMENT ON COLUMN place.is_active IS '활성화 여부';
COMMENT ON COLUMN place.is_deleted IS '삭제 여부';
COMMENT ON COLUMN place.created_at IS '생성 날짜';
COMMENT ON COLUMN place.updated_at IS '수정 날짜';

CREATE TABLE place_image (
    place_image_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id INTEGER NOT NULL,
    image_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_place_image_place
        FOREIGN KEY (place_id) REFERENCES place (place_id)
);

COMMENT ON TABLE place_image IS '장소 이미지';
COMMENT ON COLUMN place_image.place_image_id IS '장소 이미지 식별자';
COMMENT ON COLUMN place_image.place_id IS '장소 식별자';
COMMENT ON COLUMN place_image.image_url IS '장소 이미지 URL';
COMMENT ON COLUMN place_image.created_at IS '생성 날짜';
COMMENT ON COLUMN place_image.updated_at IS '수정 날짜';

CREATE TABLE place_scrap (
    place_scrap_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id VARCHAR(36) NOT NULL,
    place_id INTEGER NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_place_scrap_member
        FOREIGN KEY (member_id) REFERENCES member (member_id),
    CONSTRAINT fk_place_scrap_place
        FOREIGN KEY (place_id) REFERENCES place (place_id),
    CONSTRAINT uk_place_scrap_member_place UNIQUE (member_id, place_id)
);

CREATE TABLE hours (
    hours_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id INTEGER NOT NULL,
    open_date TIMESTAMP WITH TIME ZONE NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    break_start_at TIMESTAMP WITH TIME ZONE,
    break_end_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_hours_place
        FOREIGN KEY (place_id) REFERENCES place (place_id)
);

CREATE TABLE place_member_like (
    place_member_like_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id INTEGER NOT NULL,
    member_id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_place_member_like_place
        FOREIGN KEY (place_id) REFERENCES place (place_id),
    CONSTRAINT fk_place_member_like_member
        FOREIGN KEY (member_id) REFERENCES member (member_id)
);

COMMENT ON TABLE place_scrap IS '장소 스크랩';
COMMENT ON COLUMN place_scrap.place_scrap_id IS '스크랩 식별자';
COMMENT ON COLUMN place_scrap.member_id IS '유저 식별자';
COMMENT ON COLUMN place_scrap.place_id IS '장소 식별자';
COMMENT ON COLUMN place_scrap.is_deleted IS '삭제 여부';
COMMENT ON COLUMN place_scrap.created_at IS '생성 날짜';
COMMENT ON COLUMN place_scrap.updated_at IS '수정 날짜';
COMMENT ON COLUMN place_scrap.deleted_at IS '삭제 날짜';

COMMENT ON TABLE hours IS '영업시간';
COMMENT ON COLUMN hours.hours_id IS '영업시간 식별자';
COMMENT ON COLUMN hours.place_id IS '장소 식별자';
COMMENT ON COLUMN hours.open_date IS '영업 날짜';
COMMENT ON COLUMN hours.start_at IS '영업 시작 시간';
COMMENT ON COLUMN hours.end_at IS '영업 종료 시간';
COMMENT ON COLUMN hours.break_start_at IS '브레이크 시작 시간';
COMMENT ON COLUMN hours.break_end_at IS '브레이크 종료 시간';
COMMENT ON COLUMN hours.created_at IS '생성 날짜';
COMMENT ON COLUMN hours.updated_at IS '수정 날짜';

COMMENT ON TABLE place_member_like IS '장소_유저_좋아요';
COMMENT ON COLUMN place_member_like.place_member_like_id IS '장소_유저_좋아요 식별자';
COMMENT ON COLUMN place_member_like.place_id IS '장소 식별자';
COMMENT ON COLUMN place_member_like.member_id IS '유저 식별자';
COMMENT ON COLUMN place_member_like.created_at IS '생성 날짜';
