CREATE TABLE place (
    place_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    latitude DECIMAL(10, 8) NOT NULL,
    longitude DECIMAL(11, 8) NOT NULL,
    category VARCHAR(30) NOT NULL,
    view_count INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL,
    is_deleted BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_place_category CHECK (
        category IN (
            'RESTAURANT',
            'CAFE_DESSERT',
            'BAR',
            'EXHIBITION_CULTURE',
            'MOVIE_PERFORMANCE',
            'EXPERIENCE_WORKSHOP',
            'PLAY_ACTIVITY',
            'NATURE_WALK',
            'SHOPPING',
            'LANDMARK_VIEW',
            'RELAXATION_SPA'
        )
    )
);

COMMENT ON TABLE place IS '장소';
COMMENT ON COLUMN place.place_id IS '장소 식별자';
COMMENT ON COLUMN place.name IS '장소명';
COMMENT ON COLUMN place.latitude IS '위도';
COMMENT ON COLUMN place.longitude IS '경도';
COMMENT ON COLUMN place.category IS '카테고리';
COMMENT ON COLUMN place.view_count IS '조회수';
COMMENT ON COLUMN place.is_active IS '활성화 여부';
COMMENT ON COLUMN place.is_deleted IS '삭제 여부';
COMMENT ON COLUMN place.created_at IS '생성 날짜';
COMMENT ON COLUMN place.updated_at IS '수정 날짜';
